// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8NcxdmNObddmISACMXNZxLOD2l7V9WII',
    appId: '1:159578669882:web:4055767f167d9d0dd84603',
    messagingSenderId: '159578669882',
    projectId: 'course-ac9f5',
    authDomain: 'course-ac9f5.firebaseapp.com',
    storageBucket: 'course-ac9f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1wX8Sq5KMYKmcPxEIV62uM4dsPr21yo',
    appId: '1:159578669882:android:c41da9c8dd57cbabd84603',
    messagingSenderId: '159578669882',
    projectId: 'course-ac9f5',
    storageBucket: 'course-ac9f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wkqSJc1gPDtzdKawVKXgCD1ZwQ8zNUY',
    appId: '1:159578669882:ios:0cdcae668438cbcfd84603',
    messagingSenderId: '159578669882',
    projectId: 'course-ac9f5',
    storageBucket: 'course-ac9f5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wkqSJc1gPDtzdKawVKXgCD1ZwQ8zNUY',
    appId: '1:159578669882:ios:fea0c896de3e0444d84603',
    messagingSenderId: '159578669882',
    projectId: 'course-ac9f5',
    storageBucket: 'course-ac9f5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
